# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

name: "🧪 E-Signet mock: Build and publish Docker image"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: opencrvs/esignet-mock

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
          # > Note that GITHUB_SHA for this event is the last merge commit of the pull request merge branch.
          # > If you want to get the commit ID for the last commit to the head branch of the pull request, use _github.event.pull_request.head.sha_ instead.
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 7

      # The package includes symlinks to elsewhere in the monorepo, this resolves the symlinks to actual files
      - name: Resolve symlinks
        run: |
          mkdir -p images/esignet-mock
          rsync -a --copy-links packages/esignet-mock/ images/esignet-mock/

      - name: Copy yarn.lock to docker build context
        run: cp yarn.lock images/esignet-mock/yarn.lock

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          context: images/esignet-mock
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
